//----------------------------------------------------------------------------------------------------;
var fileNm = "js-exec-web/saveProcess__DOMAndJS.tjs";
if( console ) console.log( "[ S ] - " + fileNm + "----------" );
//----------------------------------------------------------------------------------------------------;

(function(){

	var cwd = process.cwd();

	//----------------------------------------------------------------------------------------------------;

	//	PARAMETER;

	//----------------------------------------------------------------------------------------------------;

	var d = <!=data=!>;

	//----------------------------------------------------------------------------------------------------;

	//	DEFINE;

	//----------------------------------------------------------------------------------------------------;

	var f0 = SUtilFsWriteStream.createDirectory__BeforCheck;
	var f1 = SUtilFsWriteStream.writeFile_UTF8;

	//----------------------------------------------------------------------------------------------------;

	//----------------------------------------------------------------------------------------------------;

	//	DOM를 컨트롤 하기;
	//	- DOM을 분석해서 원하는 바로 컨트롤 하는 로직 넣기

	//----------------------------------------------------------------------------------------------------;

	try
	{
		if( d.nm )
		{
			require( cwd + "/tjs-exec-web/nm/" + d.nm + ".dom.js" );
		}
		else
		{
			require( cwd + "/tjs-exec-web/url/" + d.url + ".dom.js" );
		}
	}
	catch( er )
	{
		window.TtwLog.error( "DOM - url Error : " + er );
		debugger;
		return 0;
	}

	//----------------------------------------------------------------------------------------------------;

	//	JS를 컨트롤 하기;
	//	- JS를 분석해서 원하는 바로 컨트롤 하는 로직 넣기

	//----------------------------------------------------------------------------------------------------;

	try
	{
		if( d.nm )
		{
			require( cwd + "/tjs-exec-web/nm/" + d.nm + ".js" );
		}
		else
		{
			require( cwd + "/tjs-exec-web/url/" + d.url + ".js" );
		}
	}
	catch( er )
	{
		window.TtwLog.error( "JS - url Error : " + er );
		debugger;
		return 0;
	}

	//----------------------------------------------------------------------------------------------------;

	//	DOM을 HTML로 저장하기;

	//----------------------------------------------------------------------------------------------------;

	f0( "../Ttw-Electron-Scraper--TestFolder" );
	var path0 = "../Ttw-Electron-Scraper--TestFolder/_scrap";f0( path0 );
	var path1 = path0 + "/" + d.url;f0( path1 );
	var path2 = path1 + "/";

	var aDate = SUtilDate.getDate__Seconds_Array( Date.now() );
	var sDate0 = "" + aDate[ 0 ] + aDate[ 1 ] + aDate[ 2 ];
	var sDate1 = "" + aDate[ 3 ];
	//*///한자리 숫자일시 앞에 0 붙이기;
	if( 1 == sDate1.length ) sDate1 = "0" + sDate1;
	//*/

	var path3 = path2 + sDate0;f0( path3 );
	var path4 = path3 + "/" + sDate1;f0( path4 );
	var path5 = path4 + "/";

	/*///한자리 숫자일시 앞에 0 붙이기;
	var sDate2 = "" + aDate[ 4 ] + "_" + aDate[ 5 ];
	/*/
	var sDate2 = "";
	if( 1 == aDate[ 4 ].length ) sDate2 = "0" + aDate[ 4 ]; else sDate2 += aDate[ 4 ];
	if( 1 == aDate[ 5 ].length ) sDate2 += "_0" + aDate[ 5 ]; else sDate2 += "_" + aDate[ 5 ];
	//*/

	f1( path5 + sDate2 + ".header.html", document.head.outerHTML );
	f1( path5 + sDate2 + ".body.html", document.body.outerHTML );

	//----------------------------------------------------------------------------------------------------;

	return 1;
})();